zsig::ZernikePolynomialsBasisT< Order, T > Class Template Reference
Zernike Polynomials Orthogonal Basis type.
#include <zpolbasist.hh>
Public Types
typedef ZernikePolynomialsBasisT< Order, T > zpolbasis_type
This class type.
typedef std::complex< T > value_type
Polynomial value type.
typedef std::vector< value_type > radial_polynomial
Radial polynomial.
Public Member Functions
ZernikePolynomialsBasisT ()
Default Constructor.
void project (T **_fxy, const unsigned int &_szx, const unsigned int &_szy)
void project (T **_fxy, zpolbasis_type **_zpb, const unsigned int &_szx, const unsigned int &_szy)
void project (const T **_fxy, const unsigned int &_szx, const unsigned int &_szy)
void project (const T **_fxy, const zpolbasis_type **_zpb, const unsigned int &_szx, const unsigned int &_szy)
Compute the projection of a function onto the Zernike basis.
void reconstruct (T **_fxy, zpolbasis_type **_zpb, const unsigned int &_szx, const unsigned int &_szy) const
void reconstruct (T **_fxy, const unsigned int &_szx, const unsigned int &_szy) const
void reconstruct (T **_fxy, const zpolbasis_type **_zpb, const unsigned int &_szx, const unsigned int &_szy) const
Compute the reconstruction of a function using the Zernike basis.
T compare (const zpolbasis_type &_zp) const
Compare two Zernike polynomials representations.
const radial_polynomial & operator[] (const unsigned &_p) const
Read/write operator of each radial polynomial.
radial_polynomial & operator[] (const unsigned &_p)
Read/write operator of each radial polynomial.
Friends
std::istream & operator>> (std::istream &in, zpolbasis_type &_z)
Input stream operator.
std::ostream & operator<< (std::ostream &out, const zpolbasis_type &_z)
Output stream operator.
Related Functions
(Note that these are not member functions.)
template<class T >
T fac (const int &_n)
Compute factorial of n: $n!$.
template<class T >
T compute_R (const unsigned &_p, const int &_q, const T &_r)
Compute Radial Polynomial: $R_{p}^{q}(\rho)$.
template<class T >
std::complex< T > compute_V (const unsigned &_p, const int &_q, const T &_r, const T &_t)
Compute Zernike Polynomial: $V_{p}^{q}(\rho, \theta)$.
template<unsigned Order, class T >
void compute_basis (ZernikePolynomialsBasisT< Order, T > **_zpb, const unsigned int &_szx, const unsigned int &_szy)
Compute Discrete Zernike Basis: all $(V_{p}^{q})[x,y]$.
Detailed Description
template<unsigned Order = 8, class T = long double> class zsig::ZernikePolynomialsBasisT< Order, T >
Zernike Polynomials Orthogonal Basis type. This class is inspired from Zernike's work:
@ARTICLE{Zernike:1934,
  author = {{F}. {Z}ernike},
  title = {{B}eugungstheorie des {S}chneidenverfahrens und seiner verbesserten {F}orm, der {P}hasenkontrastmethode},
  journal = {Physica 1},
  pages = {689--704},
  year = {1934}
}   
 The computational perspective of this class follows the basic idea on the paper:
@INPROCEEDINGS{Khotanzad:1988,
  author = {{K}hotanzad, {A}. and {H}ong, {Y}. {H}.},
  title = {Rotation invariant pattern recognition using {Z}ernike moments},
  booktitle = {9th {I}nternational {C}onference on {P}attern {R}ecognition},
  year = {1988},
  month = {Nov},
  volume = {1},
  pages = {326--328},
  doi = {http://dx.doi.org/10.1109/ICPR.1988.28233}
}   
 However, the implementation of this class targets (and follows more closely) the paper (first-authored by me):
@ARTICLE{Maximo:2011,
  author = {A. Maximo and R. Patro and A. Varshney and R. Farias},
  title = {A Robust and Rotationally Invariant Local Surface Descriptor with Applications to Non-local Mesh Processing},
  journal = {Graphical Models},
  volume = {In Press, Accepted Manuscript},
  number = {}
  pages = { - },
  year = {2011},
  issn = {1524-0703},
  doi = {http://dx.doi.org/10.1016/j.gmod.2011.05.002}
}   
Note
For higher order Zernike Polynomials high-precision number type is required. For instance, eighth-order basis reaches big numbers when computing the factorial for the radial polynomial $R_{p}^{q}(\rho)$ given in equation (2) of [Maximo:2011] and computed in compute_R.
Template Parameters
O defines Zernike target radial order
T defines number precision
Examples:
example_zpol.cc, and example_zproj.cc.
Definition at line 162 of file zpolbasist.hh.
Member Typedef Documentation
template<unsigned Order = 8, class T = long double> typedef std::vector< value_type > zsig::ZernikePolynomialsBasisT< Order, T >::radial_polynomial
Radial polynomial.
Definition at line 168 of file zpolbasist.hh.
template<unsigned Order = 8, class T = long double> typedef std::complex< T > zsig::ZernikePolynomialsBasisT< Order, T >::value_type
Polynomial value type.
Definition at line 167 of file zpolbasist.hh.
template<unsigned Order = 8, class T = long double> typedef ZernikePolynomialsBasisT< Order, T > zsig::ZernikePolynomialsBasisT< Order, T >::zpolbasis_type
This class type.
Definition at line 166 of file zpolbasist.hh.
Constructor & Destructor Documentation
template<unsigned Order = 8, class T = long double> zsig::ZernikePolynomialsBasisT< Order, T >::ZernikePolynomialsBasisT () [inline]
Default Constructor.
This class does not store: q[-4, -2, 0, 2, 4] instead it stores only: q[0, 2, 4]; since the complex conjugate of q and -q are the same V_{p}^{q} = V*_{p}^{-q}.
Definition at line 176 of file zpolbasist.hh.
Member Function Documentation
template<unsigned Order = 8, class T = long double> T zsig::ZernikePolynomialsBasisT< Order, T >::compare (const zpolbasis_type & _zp) const [inline]
Compare two Zernike polynomials representations.
The representation of a function is given by the Zernike coefficients computed by the projection into the basis. This method compares this polynomial coefficients with a given another polynomial coefficients computing the Euclidean distance between the two in Zernike space.
Parameters
_zp Zernike polynomial to compare to
Returns
Euclidean distance between Zernike coefficients
Definition at line 390 of file zpolbasist.hh.
template<unsigned Order = 8, class T = long double> const radial_polynomial& zsig::ZernikePolynomialsBasisT< Order, T >::operator[] (const unsigned & _p) const [inline]
Read/write operator of each radial polynomial.
Parameters
_p Radial order
Returns
Constant radial polynomial of order _p
Definition at line 408 of file zpolbasist.hh.
template<unsigned Order = 8, class T = long double> radial_polynomial& zsig::ZernikePolynomialsBasisT< Order, T >::operator[] (const unsigned & _p) [inline]
Read/write operator of each radial polynomial.
Parameters
_p Radial order
Returns
Radial polynomial of order _p
Definition at line 415 of file zpolbasist.hh.
template<unsigned Order = 8, class T = long double> void zsig::ZernikePolynomialsBasisT< Order, T >::project (const T ** _fxy, const zpolbasis_type ** _zpb, const unsigned int & _szx, const unsigned int & _szy) [inline]
Compute the projection of a function onto the Zernike basis.
This method projects a function onto the Zernike Polynomials Orthogonal Basis as described in equation (3) from [Maximo:2011] (the discrete version). This projection is the $(z_{p}^{q}(f))[x,y]$ associated with all possible orders $p$ and repetitions $q$ as follows:
 z_{p}^{q}(f) = \frac{p+1}{\pi} \sum_{ (x,y) \in \mathbf{S} } (\bar{V_{p}}^{q})[x,y] f[x,y] 
The domain of the function $f(x,y)$ is considered to be a discrete grid (of a given size) in the range [-1, 1] and it is converted to polar coordinates $(\rho, \theta)$, evaluating only in the unit circle (where the Zernike basis is defined) centered at the origin.
Note
This method uses the Discret Zernike Basis: $(V_{p}^{q})[x,y]$ (computed by compute_basis); which can be pre-computed and stored since the basis is valid to project any function in the same normalized domain.
Parameters
_fxy Discrete function to look up values (at [x, y] or _fxy[x][y])
_zpb Zernike Polynomials Basis for each [x, y]
_szx Function domain size on the x-direction
_szy Function domain size on the y-direction
Definition at line 271 of file zpolbasist.hh.
template<unsigned Order = 8, class T = long double> void zsig::ZernikePolynomialsBasisT< Order, T >::project (T ** _fxy, zpolbasis_type ** _zpb, const unsigned int & _szx, const unsigned int & _szy) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
_fxy Discrete function to look up values (at [x, y] or _fxy[x][y])
_zpb Zernike Polynomials Basis for each [x, y]
_szx Function domain size on the x-direction
_szy Function domain size on the y-direction
Definition at line 199 of file zpolbasist.hh.
References zsig::ZernikePolynomialsBasisT< Order, T >::project().
template<unsigned Order = 8, class T = long double> void zsig::ZernikePolynomialsBasisT< Order, T >::project (T ** _fxy, const unsigned int & _szx, const unsigned int & _szy) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
_fxy Discrete function to look up values (at [x, y] or _fxy[x][y])
_szx Function domain size on the x-direction
_szy Function domain size on the y-direction
Definition at line 186 of file zpolbasist.hh.
template<unsigned Order = 8, class T = long double> void zsig::ZernikePolynomialsBasisT< Order, T >::project (const T ** _fxy, const unsigned int & _szx, const unsigned int & _szy) [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The overloaded version of the project method does not use the Discrete Zernike Basis and, therefore, has to compute the complex conjugate of V ($(\bar{V_{p}^{q}})[x,y]$) as in compute_basis.
Parameters
_fxy Discrete function to look up values (at [x, y] or _fxy[x][y])
_szx Function domain size on the x-direction
_szy Function domain size on the y-direction
Definition at line 217 of file zpolbasist.hh.
References zsig::ZernikePolynomialsBasisT< Order, T >::compute_V().
template<unsigned Order = 8, class T = long double> void zsig::ZernikePolynomialsBasisT< Order, T >::reconstruct (T ** _fxy, const zpolbasis_type ** _zpb, const unsigned int & _szx, const unsigned int & _szy) const [inline]
Compute the reconstruction of a function using the Zernike basis.
This method reconstructs a function using the Zernike Polynomials Orthogonal Basis, considering this polynomial object as the representation of the function via Zernike coefficients and a given Zernike Polynomial Basis as $(V_{p}^{q})[x,y]$.
Parameters
_fxy Discrete function to reconstruct (at [x, y] or _fxy[x][y])
_zpb Zernike Polynomials Basis for each [x, y]
_szx Function domain size on the x-direction
_szy Function domain size on the y-direction
Definition at line 359 of file zpolbasist.hh.
template<unsigned Order = 8, class T = long double> void zsig::ZernikePolynomialsBasisT< Order, T >::reconstruct (T ** _fxy, zpolbasis_type ** _zpb, const unsigned int & _szx, const unsigned int & _szy) const [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
_fxy Discrete function to reconstruct (at [x, y] or _fxy[x][y])
_zpb Zernike Polynomials Basis for each [x, y]
_szx Function domain size on the x-direction
_szy Function domain size on the y-direction
Definition at line 301 of file zpolbasist.hh.
template<unsigned Order = 8, class T = long double> void zsig::ZernikePolynomialsBasisT< Order, T >::reconstruct (T ** _fxy, const unsigned int & _szx, const unsigned int & _szy) const [inline]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The overloaded version of the reconstruct method does not use the Discrete Zernike Basis and, therefore, has to compute V ($(V_{p}^{q})[x,y]$) as in compute_basis.
Parameters
_fxy Discrete function to reconstruct (at [x, y] or _fxy[x][y])
_szx Function domain size on the x-direction
_szy Function domain size on the y-direction
Definition at line 318 of file zpolbasist.hh.
References zsig::ZernikePolynomialsBasisT< Order, T >::compute_V().
Friends And Related Function Documentation
template<unsigned Order, class T > void compute_basis (ZernikePolynomialsBasisT< Order, T > ** _zpb, const unsigned int & _szx, const unsigned int & _szy) [related]
Compute Discrete Zernike Basis: all $(V_{p}^{q})[x,y]$.
This function computes the orthogonal basis used in equation (3) from [Maximo:2011] (the discrete version), that is the Zernike basis $(V_{p}^{q})[x,y]$ associated with all possible orders $p$ and repetitions $q$ related with the target function $f(x,y)$ to be projected, as follows:
 z_{p}^{q}(f) = \frac{p+1}{\pi} \sum_{ (x,y) \in \mathbf{S} } (\bar{V_{p}}^{q})[x,y] f[x,y] 
The domain of the function $f(x,y)$ is considered to be a discrete grid (of a given size) in the range [-1, 1] and it is converted to polar coordinates $(\rho, \theta)$, evaluating only in the unit circle (where the Zernike basis is defined) centered at the origin.
Note
This function computes only: q[0, 2, 4] (i.e. the indices qi[0, 1, 2]) and not: q[-4, -2, 0, 2, 4]; since the conjugate of q and -q are the same V_{p}^{q} = V*_{p}^{-q}.
Parameters
_zpb Zernike Polynomials Basis for each [x, y]
_szx Domain size of the x-direction
_szy Domain size of the y-direction
Template Parameters
O defines Zernike target radial order
T defines number precision
See also
ZernikePolynomialsBasisT
Definition at line 491 of file zpolbasist.hh.
template<class T > T compute_R (const unsigned & _p, const int & _q, const T & _r) [related]
Compute Radial Polynomial: $R_{p}^{q}(\rho)$.
This function computes the value returned by equation (1) from [Maximo:2011], that is the Radial Polynomial associated with order $p$ and repetition $q$ as follows:
 R_{p}^{q}(\rho) = \mathop{\sum_{k=|q|}^{p}}_{|p-q| \mathrm{even}} \frac{(-1)^{\frac{p-k}{2}} \frac{p+k}{2}!}{\frac{p-k}{2}! \frac{k-q}{2}! \frac{k+q}{2}!}\rho^{k} \label{eq:Rpq} 
Parameters
_p Radial order
_q Frequency repetition
_r Domain radius $\rho$ to compute the polynomial
Returns
Radial Polynomial $R_{p}^{q}(\rho)$
Template Parameters
T defines number precision
See also
ZernikePolynomialsBasisT
Definition at line 61 of file zpolbasist.hh.
template<class T > std::complex< T > compute_V (const unsigned & _p, const int & _q, const T & _r, const T & _t) [related]
Compute Zernike Polynomial: $V_{p}^{q}(\rho, \theta)$.
This function computes the value returned by equation (2) from [Maximo:2011], that is the Zernike Polynomial associated with order $p$ and repetition $q$ as follows:
 V_{p}^{q}(\rho, \theta) = R_{p}^{q}(\rho) e^{iq\theta} 
Parameters
_p Radial order
_q Frequency repetition
_r Domain radius $\rho$ to compute the polynomial
_t Domain angle $\theta$ to compute the polynomial
Returns
Zernike Polynomial $V_{p}^{q}(\rho, \theta)$
Template Parameters
T defines number precision
See also
ZernikePolynomialsBasisT
Definition at line 102 of file zpolbasist.hh.
template<class T > T fac (const int & _n) [related]
Compute factorial of n: $n!$.
Parameters
_n Number to compute the factorial of
Returns
Factorial of n
Template Parameters
T defines number precision
See also
ZernikePolynomialsBasisT
Definition at line 33 of file zpolbasist.hh.
template<unsigned Order = 8, class T = long double> std::ostream& operator<< (std::ostream & out, const zpolbasis_type & _z) [friend]
Output stream operator.
Parameters
out Output stream
_z Zernike Polynomials Basis to output
Returns
Output stream
Definition at line 436 of file zpolbasist.hh.
template<unsigned Order = 8, class T = long double> std::istream& operator>> (std::istream & in, zpolbasis_type & _z) [friend]
Input stream operator.
Parameters
in Input stream
_z Zernike Polynomials Basis to output
Returns
Input stream
Definition at line 423 of file zpolbasist.hh.
The documentation for this class was generated from the following file:
include/zpolbasist.hh